name: flutter_scaffold_bloc
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  auto_size_text: ^3.0.0
  beamer: ^1.5.3
  bloc: ^8.1.1
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.1.2
  formz: ^0.4.1
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  logger: ^1.1.0
  shared_preferences: ^2.0.17

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/images/
   - assets/lottie/
   - app_config_development.json
   - app_config_staging.json
   - app_config_production.json